require:
  - rubocop-performance

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true

Metrics/MethodLength:
  Max: 20
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/BlockLength:
  Max: 50

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Enabled: false
